version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradle-app
    depends_on:
      - sonarqube
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
    working_dir: /project
    command: ["/bin/bash"]
    networks:
      - ci-net
    volumes:
      - .:/project
    tty: true

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-1
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db
    networks:
      - ci-net

  db:
    image: postgres:13
    container_name: sonar-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - ci-net
    volumes:
      - sonar-db-data:/var/lib/postgresql/data

networks:
  ci-net:

volumes:
  sonar-db-data:
